services:
  add_task:
    build:
      context: ./backend/add_task
    container_name: add_task_service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  remove_task:
    build:
      context: ./backend/remove_task
    container_name: remove_task_service
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  edit_task:
    build:
      context: ./backend/edit_task
    container_name: edit_task_service
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always
    

  mark_done:
    build:
      context: ./backend/mark_done
    container_name: mark_done_service
    ports:
      - "4003:4003"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  get_tasks:
    build:
      context: ./backend/get_tasks
    container_name: get_tasks_service
    ports:
      - "4004:4004"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  search_task:
    build:
      context: ./backend/search_task
    container_name: search_task_service
    ports:
      - "4005:4005"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  sort_tasks:
    build:
      context: ./backend/sort_tasks
    container_name: sort_tasks_service
    ports:
      - "4006:4006"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  reset_tasks:
    build:
      context: ./backend/reset_tasks
    container_name: reset_tasks_service
    ports:
      - "4007:4007"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  register:
    build:
      context: ./backend/register
    container_name: register_service
    ports:
      - "4008:4008"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  login:
    build:
      context: ./backend/login
    container_name: login_service
    ports:
      - "4009:4009"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  
  delete_user:
    build:
      context: ./backend/delete_user
    container_name: delete_user_service
    ports:
      - "4010:4010"
    environment:
      - MONGO_URI=mongodb+srv://ronybubnovsky:UX4st2u29gvKGqbu@taskmanager.qjg5t.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
    restart: always

  get_tasks_nodejs:
    build:
      context: ./nodejs-services/get_tasks
    container_name: get_tasks_nodejs_service
    ports:
      - "5007:5007"
    restart: always

  reset_tasks_nodejs:
    build:
      context: ./nodejs-services/reset_tasks
    container_name: reset_tasks_nodejs_service
    ports:
      - "5001:5001"
    restart: always

  analyze_tasks:
    build:
      context: ./backend/analyze_tasks
    container_name: analyze_tasks_service
    ports:
      - "5002:5002"
    restart: always

  share_tasks:
    build:
      context: ./backend/share_tasks
    container_name: share_tasks_service
    ports:
      - "5003:5003"
    restart: always

  sync_tasks:
    build:
      context: ./backend/sync_tasks
    container_name: sync_tasks_service
    ports:
      - "5004:5004"
    restart: always


  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always